### ISSUE TITLE
Add meeting to the CNCF Community meetings calendar

### ISSUE THREAD

**Issue by brandtkeller** [cncf/public-sector-user-group#13]
# Proposal
Add the meeting invite to the [CNCF Calendar](https://www.cncf.io/calendar/)

## Questions
Is there a reason why we might not have already done so? @onlydole

**Comment by onlydole** [comment]
Howdy, @brandtkeller! That calendar is more for CNCF Project Community-centric (rather than end user centric).

In the long-term, we're going to be moving all our meetings into the Linux Foundation's LFX platform for better management and features like meeting transcripts/recordings/etc via: https://lfx.linuxfoundation.org

That link will be the best place to see which meetings you're invited to and manage them accordingly - if you have any other questions, let me know and I'm happy to help!

**Comment by brandtkeller** [comment]
> Howdy, @brandtkeller! That calendar is more for CNCF Project Community-centric (rather than end user centric).
> 
> In the long-term, we're going to be moving all our meetings into the Linux Foundation's LFX platform for better management and features like meeting transcripts/recordings/etc via: https://lfx.linuxfoundation.org
> 
> That link will be the best place to see which meetings you're invited to and manage them accordingly - if you have any other questions, let me know and I'm happy to help!

@onlydole Thank you for the context! I tend to use that calendar for other initiatives as a source of truth. If migration to the LFX platform allows that then wonderful! As long as we have a calendar to reference in the readme for which people can copy to their own calendars then we'd be set.

**Comment by onlydole** [comment]
Awesomeness :smile: we are going to eventually move all our meetings to that platform (and remove some of our woes with more manual GCal changes/edits). I'll keep you and this crew posted, and will add some details to the README for how folks can get involved.

**Comment by onlydole** [comment]
Updated the README with the latest info!
